export const selectionCircleSize = [
  { size: 22 },
  { size: 32 },
  { size: 46 },
  { size: 62 },
  { size: 72 },
  { size: 94 },
  { size: 110 },
  { size: 122 },
  { size: 146 },
  { size: 224 },
  { size: 22, dashed: true },
  { size: 32, dashed: true },
  { size: 46, dashed: true },
  { size: 62, dashed: true },
  { size: 72, dashed: true },
  { size: 94, dashed: true },
  { size: 110, dashed: true },
  { size: 122, dashed: true },
  { size: 146, dashed: true },
  { size: 224, dashed: true },
];
