export enum InputEvents {
  TogglePlay = "TogglePlay",
  SpeedUp = "SpeedUp",
  SpeedDown = "SpeedDown",
  SkipForward = "SkipForward",
  SkipBackwards = "SkipBackwards",
  ToggleMenu = "ToggleMenu",
  ToggleReplayPosition = "ToggleReplayPosition",
  ToggleUnitSelection = "ToggleUnitSelection",
  ToggleMinimap = "ToggleMinimap",
  ToggleResources = "ToggleResources",
  ToggleProduction = "ToggleProduction",
  ToggleAll = "ToggleAll",
  ToggleUnitInformation = "ToggleUnitInformation",
  ToggleElevation = "ToggleElevation",
  ToggleCursor = "ToggleCursor",
  ToggleCameraMode = "ToggleCameraMode",
};