export default {
  TogglePlay: "TogglePlay",
  ToggleGrid: "ToggleGrid",
  ToggleMenu: "ToggleMenu",
  ToggleReplayPosition: "ToggleReplayPosition",
  ToggleUnitSelection: "ToggleUnitSelection",
  ToggleMinimap: "ToggleMinimap",
  ToggleResources: "ToggleResources",
  ToggleProduction: "ToggleProduction",
  ToggleAll: "ToggleAll",
  ToggleUnitInformation: "ToggleUnitInformation",
  ToggleElevation: "ToggleElevation",
  TruckLeft: "TruckLeft",
  TruckRight: "TruckRight",
  AzimuthLeft: "AzimuthLeft",
  AzimuthRight: "AzimuthRight",
  PolarUp: "PolarUp",
  PolarDown: "PolarDown",
  MoveForward: "MoveForward",
  MoveBackward: "MoveBackward",
  ResetCamera: "ResetCamera",
};
