export const GET_APPCACHE_PATH = "getAppCachePath";
export const OPEN_FILE = "openFile";
export const OPEN_MAP_DIALOG = "OPEN_MAP_DIALOG";
export const OPEN_REPLAY_DIALOG = "OPEN_REPLAY_DIALOG";
export const LOAD_ALL_DATA_FILES = "loadAllDataFiles";
export const GET_SETTINGS = "GET_SETTINGS";
export const SET_SETTINGS = "SET_SETTINGS";
export const SETTINGS_CHANGED = "SETTINGS_CHANGED";
export const GET_LANGUAGE = "GET_LANGUAGE";
export const SELECT_FOLDER = "SELECT_FOLDER";
export const LOG_MESSAGE = "LOG_MESSAGE";
export const EXIT = "EXIT";

export default {
  GET_APPCACHE_PATH,
  OPEN_FILE,
  LOAD_ALL_DATA_FILES,
  GET_SETTINGS,
  SET_SETTINGS,
  SETTINGS_CHANGED,
  GET_LANGUAGE,
  SELECT_FOLDER,
  OPEN_MAP_DIALOG,
  OPEN_REPLAY_DIALOG,
  LOG_MESSAGE,
  EXIT,
};
