export const OPEN_FILE = "openFile";
export const OPEN_MAP_DIALOG = "OPEN_MAP_DIALOG";
export const OPEN_REPLAY_DIALOG = "OPEN_REPLAY_DIALOG";
export const OPEN_DEMO_REPLAY = "OPEN_DEMO_REPLAY";
export const GET_SETTINGS = "GET_SETTINGS";
export const SET_SETTINGS = "SET_SETTINGS";
export const SELECT_FOLDER = "SELECT_FOLDER";
export const LOG_MESSAGE = "LOG_MESSAGE";
export const EXIT = "EXIT";
export const LOAD_REPLAY_FROM_FILE = "LOAD_REPLAY_FROM_FILE";
export const LOAD_CHK_FROM_FILE = "LOAD_CHK_FROM_FILE";
export const DOWNLOAD_UPDATE = "DOWNLOAD_UPDATE";
export const OPEN_URL = "OPEN_URL";

export const OPEN_CASCLIB = "OPEN_CASCLIB";
export const CLOSE_CASCLIB = "CLOSE_CASCLIB";
export const OPEN_CASCLIB_FILE = "OPEN_CASCLIB_FILE";
export const OPEN_CASCLIB_BATCH = "OPEN_CASCLIB_BATCH";

export const UPDATE_PLUGIN_CONFIG = "UPDATE_PLUGIN_CONFIG";
export const RELOAD_PLUGINS = "RELOAD_PLUGINS";
export const DISABLE_PLUGIN = "DISABLE_PLUGIN";
export const DELETE_PLUGIN = "DELETE_PLUGIN";
export const ENABLE_PLUGINS = "ENABLE_PLUGINS";
export const INSTALL_PLUGIN = "INSTALL_PLUGIN";

export const ON_PLUGIN_CONFIG_UPDATED = "ON_PLUGIN_CONFIG_UPDATED";
export const ON_PLUGINS_ENABLED = "ON_PLUGINS_ENABLED";
export const ON_PLUGINS_INITIAL_INSTALL_ERROR = "ON_PLUGINS_INITIAL_INSTALL_ERROR";
export const ON_PLUGINS_INITIAL_INSTALL = "ON_PLUGINS_INITIAL_INSTALL";