// remote = privileged process of some sort
// In electron that would be main process

export const OPEN_FILE_REMOTE = "OPEN_FILE_REMOTE";
export const WRITE_FILE_REMOTE = "WRITE_FILE_REMOTE";

export const GET_USER_SETTINGS_REMOTE = "GET_USER_SETTINGS_REMOTE";
export const SAVE_USER_SETTINGS_REMOTE = "SAVE_USER_SETTINGS_REMOTE";

export const SHOW_FOLDER_DIALOG_REMOTE = "SHOW_FOLDER_DIALOG_REMOTE";
export const LOG_MESSAGE_REMOTE = "LOG_MESSAGE_REMOTE";

export const OPEN_URL_REMOTE = "OPEN_URL_REMOTE";

export const LOAD_DAT_FILES_REMOTE = "LOAD_DAT_FILES_REMOTE";

export const OPEN_CASCLIB_REMOTE = "OPEN_CASCLIB_REMOTE";
export const CLOSE_CASCLIB_REMOTE = "CLOSE_CASCLIB_REMOTE";
export const OPEN_CASCLIB_FILE_REMOTE = "OPEN_CASCLIB_FILE_REMOTE";
export const OPEN_CASCLIB_BATCH_REMOTE = "OPEN_CASCLIB_BATCH_REMOTE";

export const SAVE_PLUGIN_CONFIG_REMOTE = "SAVE_PLUGIN_CONFIG_REMOTE";
export const DELETE_PLUGIN_REMOTE = "DELETE_PLUGIN_REMOTE";
export const ACTIVATE_PLUGINS_REMOTE = "ACTIVATE_PLUGINS_REMOTE";

export const EDITOR_GET_TS_COMPLETIONS_AT_POS_REMOTE = "EDITOR_GET_TS_COMPLETIONS_AT_POS_REMOTE";
export const EDITOR_SET_CONTENTS_REMOTE = "EDITOR_SET_CONTENTS_REMOTE";

export const SEARCH_NPM_PACKAGES_REMOTE = "SEARCH_NPM_PACKAGES_REMOTE";


// when a file dialog from the main process is opened, the main process will send this event to the renderer process
export const QUEUE_FILES_LOCAL = "QUEUE_FILES_LOCAL";
export const CLEAR_REPLAY_DIALOG_LOCAL = "CLEAR_REPLAY_DIALOG_LOCAL";

export const OPEN_ISCRIPTAH_LOCAL = "OPEN_ISCRIPTAH_LOCAL";

export const EXEC_MACRO_LOCAL = "EXEC_MACRO_LOCAL";

export const GO_TO_START_PAGE_LOCAL = "GO_TO_START_PAGE_LOCAL";

export const RELOAD_PLUGINS_LOCAL = "RELOAD_PLUGINS_LOCAL";
export const ON_PLUGINS_ACTIVATED_LOCAL = "ON_PLUGINS_ACTIVATED_LOCAL";



// used both ways
export const INVOKE_BROWSER_WINDOW = "INVOKE_BROWSER_WINDOW";
export const INVOKE_BROWSER_WINDOW_RESPONSE = "INVOKE_BROWSER_WINDOW_RESPONSE";
export const SEND_BROWSER_WINDOW = "SEND_BROWSER_WINDOW";

export const DEACTIVATE_PLUGIN = "DEACTIVATE_PLUGIN";

export const enum InvokeBrowserTarget {
    Game = "game",
    CommandCenter = "command-center",
}

export const enum BrowserTargetPayloadType {
    PluginMacroMethodCatalog = "pluginMacroMethodCatalog",
    GameTimeApiMethodCatalog = "gameTimeApiMethodCatalog",
}

export const DOWNLOAD_PLUGIN = "DOWNLOAD_PLUGIN";
export const LOAD_REMOTE_PLUGIN_METADATA = "LOAD_REMOTE_PLUGIN_METADATA";

export const ON_PLUGINS_INITIAL_INSTALL_ERROR_LOCAL = "ON_PLUGINS_INITIAL_INSTALL_ERROR_LOCAL";
export const ON_PLUGINS_INITIAL_INSTALL_LOCAL = "ON_PLUGINS_INITIAL_INSTALL";

